name: Node CI

on:
  push:
    branches:
      - master
      - 'releases/*'

  pull_request:
    branches:
      - master

jobs:
  build:
    # os for run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # can run multiples version paralell
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: say Hello Master
      run: echo Hello master
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
  
  deploy:
    name: deploy job
    runs-on: ubuntu-latest
    needs: [build]

    steps: 
    - name: echo deploy successed 
      env:
        NAME: Jonathan
      run: |
        echo deploy $NAME

